# EfficientViT-B1 (Medium) - Stage 3 Fine-Tuning
BASE: ['base_stage3.yaml']

MODEL:
  NAME: ES-EV-M-Stage3
  BACKBONE: efficientvit_b1
  PRETRAINED: checkpoints/efficient_sam3_ev_m_mobileclip_s0_5p.pt

OUTPUT: output_stage3/es_ev_m
TAG: default
